
slug = "issue-3"
number = 3
title = "Issue 3"


[[article]]
file = "how-rse-index-top-20k-crates.md"
title = "How Rust Search Extension Indexes Top 20k Crates"
author = "folyd"
pub_date = "2023-03-11"
topic = ["engineering"]
publish = true
featured = true
